version: '3.8'

services:
  sqs:
    image: softwaremill/elasticmq:latest
    container_name: sqs
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/elasticmq.conf

  scraper:
    container_name: scraper
    build:
      context: ./scraper
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ENDPOINT_URL=http://sqs:9324
      - SQS_QUEUE_URL=http://sqs:9324/queue/data-raw-q
    depends_on:
      - sqs

  processor:
    container_name: processor
    build:
      context: ./processor
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ENDPOINT_URL=http://sqs:9324
      - SQS_QUEUE_URL=http://sqs:9324/queue/data-raw-q
    depends_on:
      - sqs
    command: python -u spotify_processor.py

networks:
  default:
    name: spotify_chart_network

volumes:
  postgres_data: