service: data-pipeline

frameworkVersion: ">=3.0.0"

provider:
  name: aws
  runtime: python3.8
  region: us-west-1
  stage: local

functions:
  receiver:
    handler: processor/spotify_processor.add_details
    events:
      - sqs: arn:aws:sqs:us-west-1:000000000000:data-raw-q

resources:
  Resources:
    DataRawQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: data-raw-q

plugins:
  - serverless-python-requirements
  - serverless-offline-sqs-external
  - serverless-offline

custom:
  serverless-offline-sqs-external:
    autoCreate: true
    https: false
    apiVersion: '2012-11-05'
    host: sqs
    port: 9324
    region: us-west-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
